Develop storage code error
C-Accel-CRIPT/cript pull request #64
Opened 2022-11-29 00:08 UTC by nh916

# Changes
A custom Exception was written and added to _src/cript/storage_clients/exceptions.py_ that can be raised whenever a user is trying to connect to a storage client (Globus, S3) and gives an invalid authentication code.

The exception was implemented in _src/cript/storage_clients/globus.py_ within a try except block

``` python
from .exceptions import InvalidAuthCode, FileUploadError, FileDownloadError
        try:
            token_response = self.auth_client.oauth2_exchange_code_for_tokens(auth_code)
        except globus_sdk.services.auth.errors.AuthAPIError as error:
            raise InvalidAuthCode
```

## Limitations
I have implemented the Exception for Globus storage only.

## Before
When a user would give an invalid authentication code here is the error they would get in the terminal

``` bash
....
File "C:\Users\navid\OneDrive\Desktop\MIT\cript-SDK\src\cript\storage_clients\globus.py", line 157, in set_tokens
    token_response = self.auth_client.oauth2_exchange_code_for_tokens(auth_code)
  File "C:\Users\navid\OneDrive\Desktop\MIT\cript-excel-uploader\venv\lib\site-packages\globus_sdk\services\auth\client\base.py", line 245, in oauth2_exchange_code_for_tokens
    return self.current_oauth2_flow_manager.exchange_code_for_tokens(auth_code)
  File "C:\Users\navid\OneDrive\Desktop\MIT\cript-excel-uploader\venv\lib\site-packages\globus_sdk\services\auth\flow_managers\native_app.py", line 213, in exchange_code_for_tokens
    return self.auth_client.oauth2_token(
  File "C:\Users\navid\OneDrive\Desktop\MIT\cript-excel-uploader\venv\lib\site-packages\globus_sdk\services\auth\client\base.py", line 453, in oauth2_token
    self.post(
  File "C:\Users\navid\OneDrive\Desktop\MIT\cript-excel-uploader\venv\lib\site-packages\globus_sdk\client.py", line 155, in post
    return self.request(
  File "C:\Users\navid\OneDrive\Desktop\MIT\cript-excel-uploader\venv\lib\site-packages\globus_sdk\client.py", line 310, in request
    raise self.error_class(r)
globus_sdk.services.auth.errors.AuthAPIError: ('POST', 'https://auth.globus.org/v2/oauth2/token', None, 400, 'Error', '{"error":"invalid_grant"}')
```

## After
With the new Exception here is the error the users would get when they input an invalid authentication code for Globus

``` bash
....
File "C:\Users\navid\OneDrive\Desktop\MIT\cript-SDK\src\cript\storage_clients\globus.py", line 160, in set_tokens
    raise InvalidAuthCode
cript.storage_clients.exceptions.InvalidAuthCode: Unable to authenticate with storage client. Please use a valid Authentication code
```

# Tests
I manually tested this with the Excel Uploader because that uses the SDK under the hood. I installed the SDK in edit mode `pip install -e ..\cript-SDK\` and when I got to the Globus Authentication code screen I would enter an invalid authentication code and get the errors in the terminal

2022-11-29 01:04 UTC, dylanwal requested changes

2022-11-29 01:04 UTC, dylanwal commented on src/cript/storage_clients/globus.py
> +from .exceptions import InvalidAuthCode, FileUploadError, FileDownloadError
'absolute imports' are preferred over 'relative imports'.
change to `from cript.exceptions import InvalidAuthCode, FileUploadError, FileDownloadError`

2022-11-30 01:08 UTC, dylanwal approved these changes

2022-11-30 03:17 UTC, CVilla17 approved these changes
Looks great man! Nice work :)

2022-11-30 22:49 UTC, merged